<html>
  <!-- 使用try...捕获块返回函数的结果或适当的错误。 -->

  <!-- 如果捕获的对象不是错误，请使用它创建一个新的错误。 -->
  <div class="selector">>_></div>
  <div class="selector">2</div>
  <script>
    const attempt = (fn, ...args) => {
      try {
        return fn(...args)
      } catch (e) {
        return e instanceof Error ? e : new Error(e)
      }
    }

    var elements = attempt(function (selector) {
      return document.querySelectorAll(selector)
    }, ">_>")
    if (elements instanceof Error) elements = [] // elements = []
  </script>
</html>
